apiVersion: v1
kind: Service
metadata:
  name: grafana-agent-flow
spec:
  selector:
    app: grafana-agent-flow
  ports:
    - name: agent-svc
      protocol: TCP
      port: 12345
      targetPort: agent-port
    - name: agent-grpc-svc
      protocol: TCP
      port: 4317
      targetPort: grpc-port
    - name: agent-http-svc
      protocol: TCP
      port: 4318
      targetPort: http-port
