apiVersion: v1
kind: Service
metadata:
  name: trace-app-golang
spec:
  selector:
    app: trace-app-golang
  ports:
    - name: trace-svc
      protocol: TCP
      port: 80
      targetPort: trace-app
